/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7n6TWEtca3W
 */


export function Featured() {
    return (
      <section className="w-full py-12">
        <div className="container grid grid-cols-1 items-start gap-6 px-4 md:gap-8 lg:grid-cols-2 xl:grid-cols-4 xl:gap-10">
          <div className="flex flex-col gap-2">
            <img
              alt="Product image"
              className="aspect-square rounded-lg object-cover"
              height="300"
              src="https://dz.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/55/1615/1.jpg?5316"
              width="300"
            />
            <div className="flex flex-col gap-1.5">
              <h3 className="font-semibold text-lg">Vintage Leather Messenger Bag</h3>
              <p className="font-semibold">$79.99</p>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <img
              alt="Product image"
              className="aspect-square rounded-lg object-cover"
              height="300"
              src="https://dz.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/50/9635/1.jpg?8508"
              width="300"
            />
            <div className="flex flex-col gap-1.5">
              <h3 className="font-semibold text-lg">Classic Aviator Sunglasses</h3>
              <p className="font-semibold">$49.99</p>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <img
              alt="Product image"
              className="aspect-square rounded-lg object-cover"
              height="300"
              src="https://dz.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/69/7715/5.jpg?0696"
              width="300"
            />
            <div className="flex flex-col gap-1.5">
              <h3 className="font-semibold text-lg">Retro Bluetooth Speaker</h3>
              <p className="font-semibold">$29.99</p>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <img
              alt="Product image"
              className="aspect-square rounded-lg object-cover"
              height="300"
              src="https://dz.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/06/6235/1.jpg?9527"
              width="300"
            />
            <div className="flex flex-col gap-1.5">
              <h3 className="font-semibold text-lg">Wireless Earbuds Pro</h3>
              <p className="font-semibold">$99.99</p>
            </div>
          </div>
        </div>
      </section>
    )
  }